version: 2.1

orbs:
  swissknife: roopakv/swissknife@0.27.0
 
aliases:
  - &cache-save-key v1-dependencies-{{ checksum "Gemfile.lock" }}
  - &cache-restore-keys
    - v1-dependencies-{{ checksum "Gemfile.lock" }}
    - v1-dependencies-
only-master: &only-master
  branches:
      only:
        - master

executors:
  app-executor:
    docker:
      - image: circleci/ruby:2.6.0
        environment:
          PGHOST: localhost
          RAILS_ENV: test
      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: attendance
          POSTGRES_DB: attendance_test
    git-executor:
        docker:
          - image: alphine/git:1.0.7

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys: *cache-restore-keys
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - swissknife/fail_if_dirty:
          pattern: Gemfile.lock
          custom-error-message: Gemfile.lock is outdated with the Gemfile. Fix it by executing "bundle install" and commit the Gemfile.lock changes.
      - save_cache:
          paths:
            - ./vendor/bundle
          key: *cache-save-key

  deploy_to_heroku:
    parameters:
      app_name:
        type: string
    steps:
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/<< parameters.app_name >>.git master

jobs:
  test:
    executor: app-executor
    working_directory: ~/attendance
    steps:
      - setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Migrate database
          command: bundle exec rake db:migrate
      - run:
          name: Run rspec in parallel
          command: bundle exec rspec

  deploy:
    executor: git-executor
    steps:
      - checkout
      - deploy_to_heroku:
          app_name: $APP_NAME
    
workflows:
  workflow:
    jobs:
      - test
      - deploy:
          type: approval
          requires:
            - test
          # filters: 
          #   <<: *only-master
